
remote_theme: just-the-docs/just-the-docs


# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: INE datos
description: Análisis estadístico con datos del INE

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://JuanCervigon.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#yo permalink: pretty
#yo exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
#yo , "docs/tests/"
#yo ]

# Regression tests
# By default, the pages in /docs/tests are excluded when the ste is built.
# To include them, comment-out the relevant line above.
# Uncommenting the following line doesn't work - see https://github.com/jekyll/jekyll/issues/4791
# include: ["docs/tests/"]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
# Supports true (default) or false
#yo search_enabled: true
#yo search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  #yo heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  #yo previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  #yo preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  #yo preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  #yo tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  #yo rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  #yo button: false
  
#yo he deshabilitado search.button
search.button: false

# Enable or disable heading anchors
#yo heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Ir al repositorio GitHub":
     - "https://github.com/JuanCervigon/JuanCervigon.github.io/tree/main/docs"

# Makes Aux links open in a new tab. Default is false
#yo aux_links_new_tab: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
#yo nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
#yo back_to_top: true
#yo back_to_top_text: "Back to top"

#yo footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
#yo last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#yo last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# Footer "Edit this page on GitHub" link text
#yo gh_edit_link: true # show or hide edit this page link
#yo gh_edit_link_text: "Edit this page on GitHub"
#yo gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
#yo gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
#yo gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
#yo color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#yo ga_tracking: UA-2709176-10
#yo ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

#yo plugins:
#yo  - jekyll-seo-tag

#yo kramdown:
#yo   syntax_highlighter_opts:
#yo     block:
#yo       line_numbers: false

#yo compress_html:
#yo   clippings: all
#yo   comments: all
#yo   endings: all
#yo   startings: []
#yo   blanklines: false
#yo   profile: false
  # ignore:
  #   envs: all
